### ISSUE TITLE
something weird with practitioners

### ISSUE THREAD

**Issue by cmcnamara87** [Bio-LarK/skeletome-archive#168]
Something weird is going on with practitioners. I'm not sure what is going on, but now I have a practitioner without an ID so its impossible to delete

```
{
practitioner_id: "",
practitioner_first_name: "Craig",
practitioner_last_name: "McNamara",
phone_number: "[test, hello, world, again]",
mobile_number: "[test, hello, world, again]",
fax_number: "[test, hello, world, again]",
institution: "[test, hello, world, again]",
department: "[test, hello, world, again]",
provider_number: [
"test",
"hello",
"world",
"again"
],
email: "[test, hello, world, again]",
address: [ ]
}
```

**Comment by tudorgroza** [comment]
How did you get this? Especially since I see that all the fields have the same value - I thought I've fixed this bug ... hmmm.

**Comment by cmcnamara87** [comment]
Not sure how I got it, was testing stuff out, and the next thing I knew the patient had no ID.

**Comment by tudorgroza** [comment]
Weird ... I'll have a look into it.
