### ISSUE TITLE
Deleting patient isnt working.

### ISSUE THREAD

**Issue by cmcnamara87** [Bio-LarK/skeletome-archive#169]
Running `http://118.138.242.77:7171/api/patients/my` gives 
```
{
        "patient_id": "b9e0f7d24b804cd5",
        "user_id": "uid_1",
        "user_first_name": "First name",
        "user_last_name": "Last name",
        "patient_first_name": "",
        "patient_last_name": "",
        "patient_alias": "Alias",
        "patient_creation_date": 1433390501627,
        "patient_last_update": 1433462400000
    },
    ```

Then when trying DELETE `http://118.138.242.77:7171/api/patients/b9e0f7d24b804cd5` getting a 404.

**Comment by tudorgroza** [comment]
It's a feature ... not a bug :)
For the time being, deleting patients, groups and users is impossible - due to all the possible implications.

**Comment by cmcnamara87** [comment]
Okay I'll leave the button in for now it just wont do anything.
